# cargo-deny gate (R23). Allow-list only licenses the lockfile actually needs.

[advisories]
yanked = "deny"

[licenses]
allow = ["MIT", "Apache-2.0", "ISC", "Unicode-3.0"]

[bans]
multiple-versions = "warn"
wildcards = "deny"
allow-wildcard-paths = true

[sources]
unknown-registry = "deny"
unknown-git = "deny"
